server:
  port: 8088

spring:
  application:
    name: Instagram
  datasource:
    url: jdbc:mysql://localhost:3306/instagram
    username: root
    password: 1234
    driverClassName: com.mysql.jdbc.Driver
  #    hikari:
  #      poolName: "MyAppDataSourcePool"
  #      maximumPoolSize: 20
  #      minimumIdle: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql

# ----------------------------------------
# SpringDoc Setting
# ----------------------------------------
spring-doc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order:  DESC
    operations-sorter: method
    disable-swagger-default-url: true
  show-actuator: false

jwt:
  secret-key: thisissecretkeyofkitee@additionalwordtoget256bitsenough
  access-token-validity: 3600
  refresh-token-validity: 86400
